import { ListCountry } from './types';

const countryData: ListCountry[] = [
  { code: 'AX', name: 'AALAND ISLANDS' },
  { code: 'AF', name: 'AFGHANISTAN' },
  { code: 'AL', name: 'ALBANIA' },
  { code: 'DZ', name: 'ALGERIA' },
  { code: 'AS', name: 'AMERICAN SAMOA' },
  { code: 'AD', name: 'ANDORRA' },
  { code: 'AO', name: 'ANGOLA' },
  { code: 'AI', name: 'ANGUILLA' },
  { code: 'AQ', name: 'ANTARCTICA' },
  { code: 'AG', name: 'ANTIGUA AND BARBUDA' },
  { code: 'AR', name: 'ARGENTINA' },
  { code: 'AM', name: 'ARMENIA' },
  { code: 'AW', name: 'ARUBA' },
  { code: 'AU', name: 'AUSTRALIA' },
  { code: 'AT', name: 'AUSTRIA' },
  { code: 'AZ', name: 'AZERBAIJAN' },
  { code: 'BS', name: 'BAHAMAS' },
  { code: 'BH', name: 'BAHRAIN' },
  { code: 'BD', name: 'BANGLADESH' },
  { code: 'BB', name: 'BARBADOS' },
  { code: 'BY', name: 'BELARUS' },
  { code: 'BE', name: 'BELGIUM' },
  { code: 'BZ', name: 'BELIZE' },
  { code: 'BJ', name: 'BENIN' },
  { code: 'BM', name: 'BERMUDA' },
  { code: 'BT', name: 'BHUTAN' },
  { code: 'BO', name: 'BOLIVIA' },
  { code: 'BA', name: 'BOSNIA AND HERZEGOWINA' },
  { code: 'BW', name: 'BOTSWANA' },
  { code: 'BV', name: 'BOUVET ISLAND' },
  { code: 'BR', name: 'BRAZIL' },
  { code: 'IO', name: 'BRITISH INDIAN OCEAN TERRITORY' },
  { code: 'BN', name: 'BRUNEI DARUSSALAM' },
  { code: 'BG', name: 'BULGARIA' },
  { code: 'BF', name: 'BURKINA FASO' },
  { code: 'BI', name: 'BURUNDI' },
  { code: 'KH', name: 'CAMBODIA' },
  { code: 'CM', name: 'CAMEROON' },
  { code: 'CA', name: 'CANADA' },
  { code: 'CV', name: 'CAPE VERDE' },
  { code: 'KY', name: 'CAYMAN ISLANDS' },
  { code: 'CF', name: 'CENTRAL AFRICAN REPUBLIC' },
  { code: 'TD', name: 'CHAD' },
  { code: 'CL', name: 'CHILE' },
  { code: 'CN', name: 'CHINA' },
  { code: 'CX', name: 'CHRISTMAS ISLAND' },
  { code: 'CO', name: 'COLOMBIA' },
  { code: 'KM', name: 'COMOROS' },
  { code: 'CK', name: 'COOK ISLANDS' },
  { code: 'CR', name: 'COSTA RICA' },
  { code: 'CI', name: "COTE D'IVOIRE" },
  { code: 'CU', name: 'CUBA' },
  { code: 'CY', name: 'CYPRUS' },
  { code: 'CZ', name: 'CZECH REPUBLIC' },
  { code: 'DK', name: 'DENMARK' },
  { code: 'DJ', name: 'DJIBOUTI' },
  { code: 'DM', name: 'DOMINICA' },
  { code: 'DO', name: 'DOMINICAN REPUBLIC' },
  { code: 'EC', name: 'ECUADOR' },
  { code: 'EG', name: 'EGYPT' },
  { code: 'SV', name: 'EL SALVADOR' },
  { code: 'GQ', name: 'EQUATORIAL GUINEA' },
  { code: 'ER', name: 'ERITREA' },
  { code: 'EE', name: 'ESTONIA' },
  { code: 'ET', name: 'ETHIOPIA' },
  { code: 'FO', name: 'FAROE ISLANDS' },
  { code: 'FJ', name: 'FIJI' },
  { code: 'FI', name: 'FINLAND' },
  { code: 'FR', name: 'FRANCE' },
  { code: 'GF', name: 'FRENCH GUIANA' },
  { code: 'PF', name: 'FRENCH POLYNESIA' },
  { code: 'TF', name: 'FRENCH SOUTHERN TERRITORIES' },
  { code: 'GA', name: 'GABON' },
  { code: 'GM', name: 'GAMBIA' },
  { code: 'GE', name: 'GEORGIA' },
  { code: 'DE', name: 'GERMANY' },
  { code: 'GH', name: 'GHANA' },
  { code: 'GI', name: 'GIBRALTAR' },
  { code: 'GR', name: 'GREECE' },
  { code: 'GL', name: 'GREENLAND' },
  { code: 'GD', name: 'GRENADA' },
  { code: 'GP', name: 'GUADELOUPE' },
  { code: 'GU', name: 'GUAM' },
  { code: 'GT', name: 'GUATEMALA' },
  { code: 'GN', name: 'GUINEA' },
  { code: 'GW', name: 'GUINEA-BISSAU' },
  { code: 'GY', name: 'GUYANA' },
  { code: 'HT', name: 'HAITI' },
  { code: 'HM', name: 'HEARD AND MC DONALD ISLANDS' },
  { code: 'HN', name: 'HONDURAS' },
  { code: 'HK', name: 'HONG KONG' },
  { code: 'HU', name: 'HUNGARY' },
  { code: 'IS', name: 'ICELAND' },
  { code: 'IN', name: 'INDIA' },
  { code: 'ID', name: 'INDONESIA' },
  { code: 'IQ', name: 'IRAQ' },
  { code: 'IE', name: 'IRELAND' },
  { code: 'IL', name: 'ISRAEL' },
  { code: 'IT', name: 'ITALY' },
  { code: 'JM', name: 'JAMAICA' },
  { code: 'JP', name: 'JAPAN' },
  { code: 'JO', name: 'JORDAN' },
  { code: 'KZ', name: 'KAZAKHSTAN' },
  { code: 'KE', name: 'KENYA' },
  { code: 'KI', name: 'KIRIBATI' },
  { code: 'KW', name: 'KUWAIT' },
  { code: 'KG', name: 'KYRGYZSTAN' },
  { code: 'LA', name: "LAO PEOPLE'S DEMOCRATIC REPUBLIC" },
  { code: 'LV', name: 'LATVIA' },
  { code: 'LB', name: 'LEBANON' },
  { code: 'LS', name: 'LESOTHO' },
  { code: 'LR', name: 'LIBERIA' },
  { code: 'LY', name: 'LIBYAN ARAB JAMAHIRIYA' },
  { code: 'LI', name: 'LIECHTENSTEIN' },
  { code: 'LT', name: 'LITHUANIA' },
  { code: 'LU', name: 'LUXEMBOURG' },
  { code: 'MO', name: 'MACAU' },
  { code: 'MG', name: 'MADAGASCAR' },
  { code: 'MW', name: 'MALAWI' },
  { code: 'MY', name: 'MALAYSIA' },
  { code: 'MV', name: 'MALDIVES' },
  { code: 'ML', name: 'MALI' },
  { code: 'MT', name: 'MALTA' },
  { code: 'MH', name: 'MARSHALL ISLANDS' },
  { code: 'MQ', name: 'MARTINIQUE' },
  { code: 'MR', name: 'MAURITANIA' },
  { code: 'MU', name: 'MAURITIUS' },
  { code: 'YT', name: 'MAYOTTE' },
  { code: 'MX', name: 'MEXICO' },
  { code: 'MC', name: 'MONACO' },
  { code: 'MN', name: 'MONGOLIA' },
  { code: 'MS', name: 'MONTSERRAT' },
  { code: 'MA', name: 'MOROCCO' },
  { code: 'MZ', name: 'MOZAMBIQUE' },
  { code: 'MM', name: 'MYANMAR' },
  { code: 'NA', name: 'NAMIBIA' },
  { code: 'NR', name: 'NAURU' },
  { code: 'NP', name: 'NEPAL' },
  { code: 'NL', name: 'NETHERLANDS' },
  { code: 'AN', name: 'NETHERLANDS ANTILLES' },
  { code: 'NC', name: 'NEW CALEDONIA' },
  { code: 'NZ', name: 'NEW ZEALAND' },
  { code: 'NI', name: 'NICARAGUA' },
  { code: 'NE', name: 'NIGER' },
  { code: 'NG', name: 'NIGERIA' },
  { code: 'NU', name: 'NIUE' },
  { code: 'NF', name: 'NORFOLK ISLAND' },
  { code: 'MP', name: 'NORTHERN MARIANA ISLANDS' },
  { code: 'NO', name: 'NORWAY' },
  { code: 'OM', name: 'OMAN' },
  { code: 'PK', name: 'PAKISTAN' },
  { code: 'PW', name: 'PALAU' },
  { code: 'PA', name: 'PANAMA' },
  { code: 'PG', name: 'PAPUA NEW GUINEA' },
  { code: 'PY', name: 'PARAGUAY' },
  { code: 'PE', name: 'PERU' },
  { code: 'PH', name: 'PHILIPPINES' },
  { code: 'PN', name: 'PITCAIRN' },
  { code: 'PL', name: 'POLAND' },
  { code: 'PT', name: 'PORTUGAL' },
  { code: 'PR', name: 'PUERTO RICO' },
  { code: 'QA', name: 'QATAR' },
  { code: 'RE', name: 'REUNION' },
  { code: 'RO', name: 'ROMANIA' },
  { code: 'RU', name: 'RUSSIAN FEDERATION' },
  { code: 'RW', name: 'RWANDA' },
  { code: 'SH', name: 'SAINT HELENA' },
  { code: 'KN', name: 'SAINT KITTS AND NEVIS' },
  { code: 'LC', name: 'SAINT LUCIA' },
  { code: 'PM', name: 'SAINT PIERRE AND MIQUELON' },
  { code: 'VC', name: 'SAINT VINCENT AND THE GRENADINES' },
  { code: 'WS', name: 'SAMOA' },
  { code: 'SM', name: 'SAN MARINO' },
  { code: 'ST', name: 'SAO TOME AND PRINCIPE' },
  { code: 'SA', name: 'SAUDI ARABIA' },
  { code: 'SN', name: 'SENEGAL' },
  { code: 'CS', name: 'SERBIA AND MONTENEGRO' },
  { code: 'SC', name: 'SEYCHELLES' },
  { code: 'SL', name: 'SIERRA LEONE' },
  { code: 'SG', name: 'SINGAPORE' },
  { code: 'SK', name: 'SLOVAKIA' },
  { code: 'SI', name: 'SLOVENIA' },
  { code: 'SB', name: 'SOLOMON ISLANDS' },
  { code: 'SO', name: 'SOMALIA' },
  { code: 'ZA', name: 'SOUTH AFRICA' },
  { code: 'GS', name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' },
  { code: 'ES', name: 'SPAIN' },
  { code: 'LK', name: 'SRI LANKA' },
  { code: 'SD', name: 'SUDAN' },
  { code: 'SR', name: 'SURINAME' },
  { code: 'SJ', name: 'SVALBARD AND JAN MAYEN ISLANDS' },
  { code: 'SZ', name: 'SWAZILAND' },
  { code: 'SE', name: 'SWEDEN' },
  { code: 'CH', name: 'SWITZERLAND' },
  { code: 'SY', name: 'SYRIAN ARAB REPUBLIC' },
  { code: 'TW', name: 'TAIWAN' },
  { code: 'TJ', name: 'TAJIKISTAN' },
  { code: 'TH', name: 'THAILAND' },
  { code: 'TL', name: 'TIMOR-LESTE' },
  { code: 'TG', name: 'TOGO' },
  { code: 'TK', name: 'TOKELAU' },
  { code: 'TO', name: 'TONGA' },
  { code: 'TT', name: 'TRINIDAD AND TOBAGO' },
  { code: 'TN', name: 'TUNISIA' },
  { code: 'TR', name: 'TURKEY' },
  { code: 'TM', name: 'TURKMENISTAN' },
  { code: 'TC', name: 'TURKS AND CAICOS ISLANDS' },
  { code: 'TV', name: 'TUVALU' },
  { code: 'UG', name: 'UGANDA' },
  { code: 'UA', name: 'UKRAINE' },
  { code: 'AE', name: 'UNITED ARAB EMIRATES' },
  { code: 'GB', name: 'UNITED KINGDOM' },
  { code: 'US', name: 'UNITED STATES' },
  { code: 'UM', name: 'UNITED STATES MINOR OUTLYING ISLANDS' },
  { code: 'UY', name: 'URUGUAY' },
  { code: 'UZ', name: 'UZBEKISTAN' },
  { code: 'VU', name: 'VANUATU' },
  { code: 'VE', name: 'VENEZUELA' },
  { code: 'VN', name: 'VIET NAM' },
  { code: 'WF', name: 'WALLIS AND FUTUNA ISLANDS' },
  { code: 'EH', name: 'WESTERN SAHARA' },
  { code: 'YE', name: 'YEMEN' },
  { code: 'ZM', name: 'ZAMBIA' },
  { code: 'ZW', name: 'ZIMBABWE' },
];

export default countryData;
